/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace StakingPlatform {
  export type StakeStruct = {
    amount: BigNumberish;
    reward: BigNumberish;
    lastStakeDate: BigNumberish;
    lastRewardDate: BigNumberish;
  };

  export type StakeStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    amount: BigNumber;
    reward: BigNumber;
    lastStakeDate: BigNumber;
    lastRewardDate: BigNumber;
  };
}

export interface StakingPlatformInterface extends utils.Interface {
  functions: {
    "claim()": FunctionFragment;
    "getDetails(address)": FunctionFragment;
    "getRewardDelay()": FunctionFragment;
    "getRewardPercentage()": FunctionFragment;
    "getUnstakeDelay()": FunctionFragment;
    "setLock(bool)": FunctionFragment;
    "setRewardDelay(uint256)": FunctionFragment;
    "setRewardPercentage(uint256)": FunctionFragment;
    "setRewardToken(address)": FunctionFragment;
    "setStakingToken(address)": FunctionFragment;
    "setUnstakeDelay(uint256)": FunctionFragment;
    "stake(uint256)": FunctionFragment;
    "unstake()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claim"
      | "getDetails"
      | "getRewardDelay"
      | "getRewardPercentage"
      | "getUnstakeDelay"
      | "setLock"
      | "setRewardDelay"
      | "setRewardPercentage"
      | "setRewardToken"
      | "setStakingToken"
      | "setUnstakeDelay"
      | "stake"
      | "unstake"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(functionFragment: "getDetails", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRewardDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUnstakeDelay",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setLock", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setRewardDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardPercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUnstakeDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "unstake", values?: undefined): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDetails", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRewardDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnstakeDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setLock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRewardDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUnstakeDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;

  events: {
    "RewardDelayChanged(uint256)": EventFragment;
    "RewardRateChanged(uint256)": EventFragment;
    "UnstakeDelayChanged(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RewardDelayChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardRateChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnstakeDelayChanged"): EventFragment;
}

export interface RewardDelayChangedEventObject {
  rewardDelay: BigNumber;
}
export type RewardDelayChangedEvent = TypedEvent<
  [BigNumber],
  RewardDelayChangedEventObject
>;

export type RewardDelayChangedEventFilter =
  TypedEventFilter<RewardDelayChangedEvent>;

export interface RewardRateChangedEventObject {
  rewardPercentage: BigNumber;
}
export type RewardRateChangedEvent = TypedEvent<
  [BigNumber],
  RewardRateChangedEventObject
>;

export type RewardRateChangedEventFilter =
  TypedEventFilter<RewardRateChangedEvent>;

export interface UnstakeDelayChangedEventObject {
  unstakeDelay: BigNumber;
}
export type UnstakeDelayChangedEvent = TypedEvent<
  [BigNumber],
  UnstakeDelayChangedEventObject
>;

export type UnstakeDelayChangedEventFilter =
  TypedEventFilter<UnstakeDelayChangedEvent>;

export interface StakingPlatform extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StakingPlatformInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claim(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getDetails(
      staker: string,
      overrides?: CallOverrides
    ): Promise<[StakingPlatform.StakeStructOutput]>;

    getRewardDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRewardPercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUnstakeDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    setLock(
      value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRewardDelay(
      newRewardDelay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRewardPercentage(
      newRewardPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRewardToken(
      newRewardToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setStakingToken(
      newStakingToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUnstakeDelay(
      newUnstakeDelay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unstake(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  claim(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getDetails(
    staker: string,
    overrides?: CallOverrides
  ): Promise<StakingPlatform.StakeStructOutput>;

  getRewardDelay(overrides?: CallOverrides): Promise<BigNumber>;

  getRewardPercentage(overrides?: CallOverrides): Promise<BigNumber>;

  getUnstakeDelay(overrides?: CallOverrides): Promise<BigNumber>;

  setLock(
    value: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRewardDelay(
    newRewardDelay: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRewardPercentage(
    newRewardPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRewardToken(
    newRewardToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setStakingToken(
    newStakingToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUnstakeDelay(
    newUnstakeDelay: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stake(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unstake(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claim(overrides?: CallOverrides): Promise<void>;

    getDetails(
      staker: string,
      overrides?: CallOverrides
    ): Promise<StakingPlatform.StakeStructOutput>;

    getRewardDelay(overrides?: CallOverrides): Promise<BigNumber>;

    getRewardPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    getUnstakeDelay(overrides?: CallOverrides): Promise<BigNumber>;

    setLock(value: boolean, overrides?: CallOverrides): Promise<void>;

    setRewardDelay(
      newRewardDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setRewardPercentage(
      newRewardPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setRewardToken(
      newRewardToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setStakingToken(
      newStakingToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setUnstakeDelay(
      newUnstakeDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stake(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    unstake(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "RewardDelayChanged(uint256)"(
      rewardDelay?: BigNumberish | null
    ): RewardDelayChangedEventFilter;
    RewardDelayChanged(
      rewardDelay?: BigNumberish | null
    ): RewardDelayChangedEventFilter;

    "RewardRateChanged(uint256)"(
      rewardPercentage?: BigNumberish | null
    ): RewardRateChangedEventFilter;
    RewardRateChanged(
      rewardPercentage?: BigNumberish | null
    ): RewardRateChangedEventFilter;

    "UnstakeDelayChanged(uint256)"(
      unstakeDelay?: BigNumberish | null
    ): UnstakeDelayChangedEventFilter;
    UnstakeDelayChanged(
      unstakeDelay?: BigNumberish | null
    ): UnstakeDelayChangedEventFilter;
  };

  estimateGas: {
    claim(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getDetails(staker: string, overrides?: CallOverrides): Promise<BigNumber>;

    getRewardDelay(overrides?: CallOverrides): Promise<BigNumber>;

    getRewardPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    getUnstakeDelay(overrides?: CallOverrides): Promise<BigNumber>;

    setLock(
      value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRewardDelay(
      newRewardDelay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRewardPercentage(
      newRewardPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRewardToken(
      newRewardToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setStakingToken(
      newStakingToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUnstakeDelay(
      newUnstakeDelay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unstake(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claim(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getDetails(
      staker: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardDelay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRewardPercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUnstakeDelay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setLock(
      value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRewardDelay(
      newRewardDelay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRewardPercentage(
      newRewardPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRewardToken(
      newRewardToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setStakingToken(
      newStakingToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUnstakeDelay(
      newUnstakeDelay: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unstake(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
