/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakerSol from "./Staker.sol";
export type { stakerSol };
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export { IERC20__factory } from "./factories/IERC20__factory";
export type { StakingPlatform } from "./Staker.sol/StakingPlatform";
export { StakingPlatform__factory } from "./factories/Staker.sol/StakingPlatform__factory";
